### ISSUE TITLE
星星大小怎么控制?

### ISSUE THREAD

**Issue by flyjin** [AlexMofer/DrawableRatingBar#1]

**Comment by flyjin** [comment]
发现没办法调整图片的大小啊

**Comment by AlexMofer** [comment]
之所以叫DrawableRatingBar，就是因为其控制的是两张Drawable来达到星评效果，至于每颗星的样式就是由Drawable控制。而控件本身并不参与单个子项效果的控制。
因此：
1. 需要静态的调整图片大小（多个控件，控制大小不一），则需要设置不同大小的图片。
2. 需要动态的调整图片大小（单个控件，不同情况下大小改变），则需要自行实现大小可变的Drawable，实现方案如Path绘制或者Drawable包装一个svg矢量图，动态的改变尺寸避免失真。
最后，你需要的该功能不应该耦合在控件当中。

**Comment by flyjin** [comment]
感谢大神解答
